#!/usr/bin/env python3
import json
import socket
from pathlib import Path

SECRETS = Path('/config/state/secrets.json')
OPTIONS = Path('/data/options.json')


def _load_json(path, default):
    try:
        return json.loads(path.read_text())
    except Exception:
        return default


class AsteriskAMI:
    """Local health probe for the Asterisk Manager Interface.

    AMI belongs to Asterisk, not to any trunk/modem. This helper only checks the
    PBX-wide AMI listener using the account already generated by the add-on.
    Secrets are never returned by status().
    """

    def settings(self):
        sec = _load_json(SECRETS, {})
        opt = _load_json(OPTIONS, {})
        return {
            'host': '127.0.0.1',
            'bindaddr': '0.0.0.0',
            'port': int(opt.get('ami_port', 5038) or 5038),
            'username': str(sec.get('ami_user', 'homeassistant') or 'homeassistant'),
            'password': str(sec.get('ami_password', '') or ''),
        }

    @staticmethod
    def _recv_frame(sock, timeout=3.0):
        sock.settimeout(timeout)
        data = bytearray()
        while b'\r\n\r\n' not in data and len(data) < 1024 * 1024:
            chunk = sock.recv(4096)
            if not chunk:
                break
            data.extend(chunk)
        return data.decode(errors='replace')

    @staticmethod
    def _send_action(sock, fields):
        payload = ''.join(f'{k}: {v}\r\n' for k, v in fields.items()) + '\r\n'
        sock.sendall(payload.encode())

    def ping(self):
        cfg = self.settings()
        base = {
            'host': cfg['host'],
            'bindaddr': cfg['bindaddr'],
            'port': cfg['port'],
            'username': cfg['username'],
            'password_exposed': False,
        }
        if not cfg['password']:
            return {**base, 'ok': False, 'error': 'AMI password not initialized'}
        try:
            with socket.create_connection((cfg['host'], cfg['port']), timeout=3) as sock:
                banner = self._recv_frame(sock)
                self._send_action(sock, {
                    'Action': 'Login',
                    'Username': cfg['username'],
                    'Secret': cfg['password'],
                    'Events': 'off',
                })
                login = self._recv_frame(sock)
                if 'Response: Success' not in login:
                    return {**base, 'ok': False, 'error': 'AMI login failed', 'banner': banner.strip()[:200]}
                self._send_action(sock, {'Action': 'Ping'})
                response = self._recv_frame(sock)
                try:
                    self._send_action(sock, {'Action': 'Logoff'})
                except Exception:
                    pass
                return {
                    **base,
                    'ok': 'Response: Success' in response,
                    'banner': banner.strip()[:200],
                    'response': response[-2000:],
                }
        except Exception as e:
            return {**base, 'ok': False, 'error': str(e)}

    def status(self):
        result = self.ping()
        return {
            'enabled': True,
            'connected': bool(result.get('ok')),
            'host': result.get('host', '127.0.0.1'),
            'bindaddr': result.get('bindaddr', '0.0.0.0'),
            'port': result.get('port', 5038),
            'username': result.get('username', 'homeassistant'),
            'banner': result.get('banner', ''),
            'response': result.get('response', ''),
            'error': result.get('error', ''),
            'password_exposed': False,
        }


AMI = AsteriskAMI()
