#!/usr/bin/env python3
from http.server import ThreadingHTTPServer, BaseHTTPRequestHandler
from pathlib import Path
from urllib.parse import urlparse, parse_qs
import json, subprocess, re, glob

CONF=Path('/config/asterisk'); STATE=Path('/config/state'); PBX=STATE/'pbx.json'; SEC=STATE/'secrets.json'
DEFAULT_AUDIO_CODECS='ulaw,alaw'

def run(cmd, timeout=8):
    try:
        p=subprocess.run(cmd, shell=True, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=timeout)
        return {'ok':p.returncode==0,'code':p.returncode,'output':p.stdout[-30000:]}
    except Exception as e:
        return {'ok':False,'code':-1,'output':str(e)}

def ast(command):
    safe=command.replace('"','\\"')
    return run(f'asterisk -C {CONF}/asterisk.conf -rx "{safe}"')

def load_json(path, default):
    try: return json.loads(Path(path).read_text())
    except Exception: return default

def save_json(path, obj):
    Path(path).write_text(json.dumps(obj,indent=2,ensure_ascii=False))

def esc(v):
    return str(v).replace('\\','\\\\').replace(';','').replace('\n',' ').strip()

def token(v, default=''):
    out=re.sub(r'[^0-9A-Za-z_*#-]','',str(v or ''))
    return out or default

def number_token(v, default=''):
    out=re.sub(r'[^0-9*#]','',str(v or ''))
    return out or default

def endpoint_lines(num, secret, caller, context='from-internal', max_contacts=5, codecs=DEFAULT_AUDIO_CODECS):
    return [
        f'\n[{num}]','type=endpoint','transport=transport-udp',f'context={context}',
        'disallow=all',f'allow={codecs}',f'auth={num}',f'aors={num}',
        f'callerid={caller} <{num}>','identify_by=username,auth_username','direct_media=no',
        'rtp_symmetric=yes','force_rport=yes','rewrite_contact=yes',
        f'\n[{num}]','type=auth','auth_type=userpass',f'username={num}',f'password={secret}',
        f'\n[{num}]','type=aor',f'max_contacts={max_contacts}','remove_existing=yes','qualify_frequency=30'
    ]

def render_managed(data):
    exts=data.get('extensions',[]); trunks=data.get('sip_trunks',[]); dongles=data.get('gsm_dongles',[])
    routes=data.get('routes',{}); ht=data.get('ht503',{}) or {}
    pjs=['; AUTO-GENERATED BY ASTERISK HA GUI']
    dial=['; AUTO-GENERATED BY ASTERISK HA GUI']
    voicemail=['; AUTO-GENERATED BY ASTERISK HA GUI']

    # Managed extensions use the common PSTN-safe codec baseline. This avoids
    # endpoints negotiating Opus when this image has no Opus<->G.711 transcoder.
    for e in exts:
        num=token(e.get('extension',''))
        if not num: continue
        secret=esc(e.get('secret','')); caller=esc(e.get('callerid',num))
        context=esc(e.get('context','from-internal')); vm_pin=number_token(e.get('voicemail_pin','1234'),'1234')
        pjs += endpoint_lines(num,secret,caller,context)
        dial += [f'exten => {num},1,Dial(PJSIP/{num},45)',' same => n,VoiceMail(${EXTEN}@default,u)',' same => n,Hangup()']
        voicemail += [f'{num} => {vm_pin},{caller},']

    for t in trunks:
        name=token(t.get('name',''))
        if not name: continue
        host=esc(t.get('server','')); user=esc(t.get('username','')); pwd=esc(t.get('password',''))
        port=int(t.get('port',5060) or 5060)
        pjs += [
            f'\n[{name}]','type=registration',f'outbound_auth={name}-auth',f'server_uri=sip:{host}:{port}',
            f'client_uri=sip:{user}@{host}','retry_interval=60',
            f'\n[{name}-auth]','type=auth','auth_type=userpass',f'username={user}',f'password={pwd}',
            f'\n[{name}]','type=aor',f'contact=sip:{host}:{port}',
            f'\n[{name}]','type=endpoint','transport=transport-udp','context=from-trunk','disallow=all',
            f'allow={DEFAULT_AUDIO_CODECS}',f'outbound_auth={name}-auth',f'aors={name}','direct_media=no'
        ]

    ht_enabled=bool(ht.get('enabled',False))
    ht_user=token(ht.get('fxo_user','ht503fxo'),'ht503fxo')
    ht_secret=esc(ht.get('fxo_secret',''))
    ht_caller=esc(ht.get('callerid','Exterior'))
    ht_target=token(ht.get('incoming_target','100'),'100')
    ht_prefix=number_token(ht.get('outbound_prefix','8'),'8')
    if ht_enabled:
        pjs += endpoint_lines(ht_user,ht_secret,ht_caller,'from-ht503-fxo',1,DEFAULT_AUDIO_CODECS)
        if ht_prefix:
            dial += [
                f'exten => _{ht_prefix}X.,1,NoOp(PSTN via Grandstream HT503 FXO)',
                f' same => n,Dial(PJSIP/${{EXTEN:{len(ht_prefix)}}}@{ht_user},90)',
                ' same => n,Hangup()'
            ]

    gsm_prefix=number_token(routes.get('gsm_prefix','9'),'9')
    if dongles:
        default_d=token(dongles[0].get('name','dongle0'),'dongle0')
        dial += [f'exten => _{gsm_prefix}X.,1,NoOp(GSM via {default_d})',f' same => n,Dial(Dongle/{default_d}/${{EXTEN:{len(gsm_prefix)}}},90)',' same => n,Hangup()']

    for t in trunks:
        name=token(t.get('name','')); prefix=number_token(t.get('prefix','0'))
        if name and prefix:
            dial += [f'exten => _{prefix}X.,1,NoOp(SIP trunk {name})',f' same => n,Dial(PJSIP/${{EXTEN:{len(prefix)}}}@{name},90)',' same => n,Hangup()']

    dong=['[general]','interval=15','\n[defaults]','context=from-dongle','group=0','rxgain=0','txgain=0','autodeletesms=yes','resetdongle=yes','u2diag=-1','usecallingpres=yes','callingpres=allowed_passed_screen']
    for d in dongles:
        name=token(d.get('name',''))
        if not name: continue
        dong += [f'\n[{name}]',f'audio={esc(d.get("audio",""))}',f'data={esc(d.get("data",""))}',f'context={esc(d.get("context","from-dongle"))}',f'group={int(d.get("group",0) or 0)}',f'rxgain={int(d.get("rxgain",0) or 0)}',f'txgain={int(d.get("txgain",0) or 0)}',f'autodeletesms={"yes" if d.get("autodeletesms",True) else "no"}',f'disablesms={"yes" if d.get("disablesms",False) else "no"}']

    incoming_target=token(routes.get('incoming_target','100'),'100')
    ht_dial=['; AUTO-GENERATED BY ASTERISK HA GUI']
    if ht_enabled:
        ht_dial += [
            'exten => s,1,NoOp(Incoming PSTN via Grandstream HT503 FXO)',
            f' same => n,Goto(from-internal,{ht_target},1)',
            f'exten => _X.,1,NoOp(Incoming PSTN DID ${{EXTEN}} via Grandstream HT503 FXO)',
            f' same => n,Goto(from-internal,{ht_target},1)'
        ]

    (CONF/'pjsip_gui.conf').write_text('\n'.join(pjs)+'\n')
    (CONF/'extensions_gui.conf').write_text('\n'.join(dial)+'\n')
    (CONF/'voicemail_gui.conf').write_text('\n'.join(voicemail)+'\n')
    (CONF/'extensions_dongle_gui.conf').write_text(f'; AUTO-GENERATED\nexten => s,1,NoOp(Incoming GSM)\n same => n,Goto(from-internal,{incoming_target},1)\n')
    (CONF/'extensions_ht503_gui.conf').write_text('\n'.join(ht_dial)+'\n')
    (CONF/'dongle.conf').write_text('\n'.join(dong)+'\n')

def apply_managed(old, new):
    render_managed(new)
    results=[]
    for c in ('pjsip reload','dialplan reload','voicemail reload'):
        r=ast(c); results.append(f'$ {c}\n{r["output"]}')
    if old.get('gsm_dongles',[]) != new.get('gsm_dongles',[]):
        r=ast('module reload chan_dongle.so'); results.append(f'$ module reload chan_dongle.so\n{r["output"]}')
    return '\n'.join(results)

def usb_ports():
    out=[]
    for dev in sorted(glob.glob('/dev/ttyUSB*')+glob.glob('/dev/ttyACM*')):
        props=run(f'udevadm info --query=property --name={dev}',3)['output']; d={'device':dev}
        for line in props.splitlines():
            if '=' not in line: continue
            k,v=line.split('=',1)
            if k in ('ID_VENDOR','ID_MODEL','ID_SERIAL_SHORT','ID_USB_INTERFACE_NUM','ID_VENDOR_ID','ID_MODEL_ID','ID_PATH'): d[k.lower()]=v
        out.append(d)
    return out
