#!/usr/bin/env python3
from http.server import ThreadingHTTPServer, BaseHTTPRequestHandler
from pathlib import Path
from urllib.parse import urlparse, parse_qs
import json, subprocess, os, re, html, time, glob

CONF=Path('/config/asterisk'); STATE=Path('/config/state'); PBX=STATE/'pbx.json'; SEC=STATE/'secrets.json'
ALLOWED_FILES={p.name for p in CONF.glob('*.conf')}

def run(cmd, timeout=8):
    try:
        p=subprocess.run(cmd, shell=True, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=timeout)
        return {'ok':p.returncode==0,'code':p.returncode,'output':p.stdout[-30000:]}
    except Exception as e: return {'ok':False,'code':-1,'output':str(e)}

def ast(command):
    safe=command.replace('"','\\"')
    return run(f'asterisk -C {CONF}/asterisk.conf -rx "{safe}"')

def load_json(path, default):
    try: return json.loads(Path(path).read_text())
    except Exception: return default

def save_json(path, obj):
    Path(path).write_text(json.dumps(obj,indent=2,ensure_ascii=False))

def esc(v):
    return str(v).replace('\\','\\\\').replace(';','').replace('\n',' ').strip()

def render_managed(data):
    exts=data.get('extensions',[]); trunks=data.get('sip_trunks',[]); dongles=data.get('gsm_dongles',[]); routes=data.get('routes',{})
    pjs=['; AUTO-GENERATED BY ASTERISK HA GUI']
    dial=['; AUTO-GENERATED BY ASTERISK HA GUI']
    voicemail=['; AUTO-GENERATED BY ASTERISK HA GUI']
    for e in exts:
        num=re.sub(r'[^0-9A-Za-z_-]','',str(e.get('extension','')))
        if not num: continue
        secret=esc(e.get('secret','')); caller=esc(e.get('callerid',num)); context=esc(e.get('context','from-internal')); vm_pin=re.sub(r'[^0-9]','',str(e.get('voicemail_pin','1234'))) or '1234'
        pjs += [f'\n[{num}]', 'type=endpoint', f'context={context}', 'disallow=all', 'allow=ulaw,alaw,g722,opus', f'auth={num}', f'aors={num}', f'callerid={caller} <{num}>', 'direct_media=no', 'rtp_symmetric=yes', 'force_rport=yes', 'rewrite_contact=yes',
                f'\n[{num}]', 'type=auth', 'auth_type=userpass', f'username={num}', f'password={secret}',
                f'\n[{num}]', 'type=aor', 'max_contacts=5', 'remove_existing=yes', 'qualify_frequency=30']
        dial += [f'exten => {num},1,Dial(PJSIP/{num},45)', ' same => n,VoiceMail(${EXTEN}@default,u)', ' same => n,Hangup()']
        voicemail += [f'{num} => {vm_pin},{caller},']
    for t in trunks:
        name=re.sub(r'[^0-9A-Za-z_-]','',str(t.get('name','')))
        if not name: continue
        host=esc(t.get('server','')); user=esc(t.get('username','')); pwd=esc(t.get('password','')); port=int(t.get('port',5060) or 5060)
        pjs += [f'\n[{name}]','type=registration',f'outbound_auth={name}-auth',f'server_uri=sip:{host}:{port}',f'client_uri=sip:{user}@{host}',f'retry_interval=60',
                f'\n[{name}-auth]','type=auth','auth_type=userpass',f'username={user}',f'password={pwd}',
                f'\n[{name}]','type=aor',f'contact=sip:{host}:{port}',
                f'\n[{name}]','type=endpoint','transport=transport-udp','context=from-trunk','disallow=all','allow=ulaw,alaw,g722',f'outbound_auth={name}-auth',f'aors={name}','direct_media=no']
    gsm_prefix=re.sub(r'[^0-9*#]','',str(routes.get('gsm_prefix','9'))) or '9'
    if dongles:
        default_d=re.sub(r'[^0-9A-Za-z_-]','',str(dongles[0].get('name','dongle0')))
        dial += [f'exten => _{gsm_prefix}X.,1,NoOp(GSM via {default_d})', f' same => n,Dial(Dongle/{default_d}/${{EXTEN:{len(gsm_prefix)}}},90)', ' same => n,Hangup()']
    # SIP trunk prefix routing
    for idx,t in enumerate(trunks):
        name=re.sub(r'[^0-9A-Za-z_-]','',str(t.get('name',''))); prefix=re.sub(r'[^0-9*#]','',str(t.get('prefix','0')))
        if name and prefix:
            dial += [f'exten => _{prefix}X.,1,NoOp(SIP trunk {name})', f' same => n,Dial(PJSIP/${{EXTEN:{len(prefix)}}}@{name},90)', ' same => n,Hangup()']
    dong=['[general]','interval=15','\n[defaults]','context=from-dongle','group=0','rxgain=0','txgain=0','autodeletesms=yes','resetdongle=yes','u2diag=-1','usecallingpres=yes','callingpres=allowed_passed_screen']
    for d in dongles:
        name=re.sub(r'[^0-9A-Za-z_-]','',str(d.get('name','')))
        if not name: continue
        dong += [f'\n[{name}]',f'audio={esc(d.get("audio",""))}',f'data={esc(d.get("data",""))}',f'context={esc(d.get("context","from-dongle"))}',f'group={int(d.get("group",0) or 0)}',f'rxgain={int(d.get("rxgain",0) or 0)}',f'txgain={int(d.get("txgain",0) or 0)}',f'autodeletesms={"yes" if d.get("autodeletesms",True) else "no"}',f'disablesms={"yes" if d.get("disablesms",False) else "no"}']
    target=re.sub(r'[^0-9A-Za-z_*#-]','',str(routes.get('incoming_target','100'))) or '100'
    (CONF/'pjsip_gui.conf').write_text('\n'.join(pjs)+'\n')
    (CONF/'extensions_gui.conf').write_text('\n'.join(dial)+'\n')
    (CONF/'voicemail_gui.conf').write_text('\n'.join(voicemail)+'\n')
    (CONF/'extensions_dongle_gui.conf').write_text(f'; AUTO-GENERATED\nexten => s,1,NoOp(Incoming GSM)\n same => n,Goto(from-internal,{target},1)\n')
    (CONF/'dongle.conf').write_text('\n'.join(dong)+'\n')

def usb_ports():
    out=[]
    for dev in sorted(glob.glob('/dev/ttyUSB*')+glob.glob('/dev/ttyACM*')):
        props=run(f'udevadm info --query=property --name={dev}',3)['output']
        d={'device':dev}
        for line in props.splitlines():
            if '=' not in line: continue
            k,v=line.split('=',1)
            if k in ('ID_VENDOR','ID_MODEL','ID_SERIAL_SHORT','ID_USB_INTERFACE_NUM','ID_VENDOR_ID','ID_MODEL_ID','ID_PATH'): d[k.lower()]=v
        out.append(d)
    return out

INDEX=r'''<!doctype html><html lang="pt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Asterisk HA</title><style>
:root{font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color-scheme:dark;background:#111827;color:#e5e7eb}body{margin:0}.top{padding:18px 22px;background:#0b1220;position:sticky;top:0;z-index:2;border-bottom:1px solid #263244}.top h1{margin:0;font-size:22px}.sub{color:#93a4b8;font-size:13px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.tabs button,.btn{background:#1f2937;color:#eee;border:1px solid #374151;border-radius:9px;padding:9px 12px;cursor:pointer}.tabs button.active,.btn.primary{background:#2563eb}.wrap{padding:18px;max-width:1400px;margin:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px}.card{background:#172033;border:1px solid #263244;border-radius:13px;padding:15px}.big{font-size:25px;font-weight:700}.ok{color:#55d98b}.bad{color:#ff7b7b}pre,textarea{background:#09101d;color:#dbeafe;border:1px solid #334155;border-radius:9px;padding:10px;overflow:auto}textarea{width:100%;min-height:420px;box-sizing:border-box}input,select{background:#0b1220;color:#eee;border:1px solid #3b4a60;border-radius:8px;padding:8px;box-sizing:border-box;width:100%}label{font-size:12px;color:#a8b6ca}.row{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px;margin:8px 0}.item{padding:10px;border:1px solid #334155;border-radius:9px;margin:8px 0}.hide{display:none}.actions{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.pill{display:inline-block;padding:4px 8px;border-radius:99px;background:#243247;font-size:12px}</style></head><body>
<div class="top"><h1>☎ Asterisk 22 + Home Assistant</h1><div class="sub">PBX · PJSIP · AMI · ARI · Queues · ConfBridge · Voicemail · Recordings · chan_dongle GSM</div><div class="tabs" id="tabs"></div></div><div class="wrap" id="app"></div>
<script>
const tabs=['Dashboard','Extensões','Trunks SIP','GSM / chan_dongle','Chamadas','Configuração','Logs','Diagnóstico'];let current='Dashboard';let pbx={};
const E=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(path,opt={}){let r=await fetch(path,{headers:{'Content-Type':'application/json'},...opt});return await r.json()}
function nav(){E('#tabs').innerHTML=tabs.map(t=>`<button class="${t==current?'active':''}" onclick="current='${t}';nav();render()">${t}</button>`).join('')}
async function render(){let a=E('#app');a.innerHTML='<div class=card>A carregar…</div>';try{pbx=await api('api/pbx')}catch(e){}
if(current==='Dashboard') dashboard(a); if(current==='Extensões') extensions(a); if(current==='Trunks SIP') trunks(a); if(current==='GSM / chan_dongle') gsm(a); if(current==='Chamadas') calls(a); if(current==='Configuração') configs(a); if(current==='Logs') logs(a); if(current==='Diagnóstico') diag(a)}
async function dashboard(a){let s=await api('api/status');a.innerHTML=`<div class=grid><div class=card><div class=sub>Asterisk</div><div class="big ${s.running?'ok':'bad'}">${s.running?'ONLINE':'OFFLINE'}</div><pre>${esc(s.version||'')}</pre></div><div class=card><div class=sub>Canais ativos</div><div class=big>${s.channels}</div></div><div class=card><div class=sub>Extensões GUI</div><div class=big>${(pbx.extensions||[]).length}</div></div><div class=card><div class=sub>Dongles GSM</div><div class=big>${(pbx.gsm_dongles||[]).length}</div></div></div><div class=actions><button class="btn primary" onclick="cmd('core reload')">Reload Asterisk</button><button class=btn onclick="cmd('pjsip reload')">Reload PJSIP</button><button class=btn onclick="cmd('module reload chan_dongle.so')">Reload chan_dongle</button></div>`}
async function cmd(c){let r=await api('api/action',{method:'POST',body:JSON.stringify({action:'cli',command:c})});alert(r.output||JSON.stringify(r));render()}
function extensions(a){let x=pbx.extensions||[];a.innerHTML=`<div class=card><h2>Extensões PJSIP</h2><div id=elist>${x.map((e,i)=>`<div class=item><div class=row><div><label>Extensão</label><input id=e${i} value="${esc(e.extension)}"></div><div><label>Caller ID</label><input id=c${i} value="${esc(e.callerid)}"></div><div><label>Password SIP</label><input id=s${i} value="${esc(e.secret)}"></div><div><label>PIN Voicemail</label><input id=v${i} value="${esc(e.voicemail_pin||'1234')}"></div><div><label>Contexto</label><input id=x${i} value="${esc(e.context||'from-internal')}"></div></div><button class=btn onclick="delExt(${i})">Remover</button></div>`).join('')}</div><div class=actions><button class=btn onclick=addExt()>+ Extensão</button><button class="btn primary" onclick=saveExt()>Guardar e aplicar</button></div></div>`}
function addExt(){pbx.extensions=pbx.extensions||[];pbx.extensions.push({extension:String(100+pbx.extensions.length),callerid:'Nova extensão',secret:Math.random().toString(36).slice(2,14),voicemail_pin:'1234',context:'from-internal'});extensions(E('#app'))}function delExt(i){pbx.extensions.splice(i,1);extensions(E('#app'))}
async function saveExt(){pbx.extensions=(pbx.extensions||[]).map((e,i)=>({extension:E('#e'+i).value,callerid:E('#c'+i).value,secret:E('#s'+i).value,voicemail_pin:E('#v'+i).value,context:E('#x'+i).value}));await savePbx()}
function trunks(a){let x=pbx.sip_trunks||[];a.innerHTML=`<div class=card><h2>Trunks SIP/PJSIP</h2>${x.map((t,i)=>`<div class=item><div class=row><div><label>Nome</label><input id=tn${i} value="${esc(t.name)}"></div><div><label>Servidor</label><input id=th${i} value="${esc(t.server)}"></div><div><label>Utilizador</label><input id=tu${i} value="${esc(t.username)}"></div><div><label>Password</label><input id=tp${i} value="${esc(t.password)}"></div><div><label>Porta</label><input id=tport${i} value="${esc(t.port||5060)}"></div><div><label>Prefixo saída</label><input id=tpre${i} value="${esc(t.prefix||'0')}"></div></div><button class=btn onclick="delTrunk(${i})">Remover</button></div>`).join('')}<div class=actions><button class=btn onclick=addTrunk()>+ Trunk</button><button class="btn primary" onclick=saveTrunks()>Guardar e aplicar</button></div></div>`}
function addTrunk(){pbx.sip_trunks=pbx.sip_trunks||[];pbx.sip_trunks.push({name:'trunk'+(pbx.sip_trunks.length+1),server:'',username:'',password:'',port:5060,prefix:'0'});trunks(E('#app'))}function delTrunk(i){pbx.sip_trunks.splice(i,1);trunks(E('#app'))}
async function saveTrunks(){pbx.sip_trunks=(pbx.sip_trunks||[]).map((t,i)=>({name:E('#tn'+i).value,server:E('#th'+i).value,username:E('#tu'+i).value,password:E('#tp'+i).value,port:+E('#tport'+i).value,prefix:E('#tpre'+i).value}));await savePbx()}
async function gsm(a){let ports=await api('api/usb');let x=pbx.gsm_dongles||[];let opts=ports.map(p=>`<option value="${esc(p.device)}">${esc(p.device)} ${esc(p.id_vendor||'')} ${esc(p.id_model||'')} IF:${esc(p.id_usb_interface_num||'')}</option>`).join('');a.innerHTML=`<div class=card><h2>chan_dongle / GSM</h2><p>Portas detetadas: <span class=pill>${ports.length}</span></p><pre>${esc(JSON.stringify(ports,null,2))}</pre>${x.map((d,i)=>`<div class=item><div class=row><div><label>Nome</label><input id=dn${i} value="${esc(d.name)}"></div><div><label>Áudio</label><select id=da${i}><option>${esc(d.audio||'')}</option>${opts}</select></div><div><label>Dados/AT</label><select id=dd${i}><option>${esc(d.data||'')}</option>${opts}</select></div><div><label>Contexto</label><input id=dc${i} value="${esc(d.context||'from-dongle')}"></div><div><label>Grupo</label><input id=dg${i} value="${esc(d.group||0)}"></div><div><label>RX gain</label><input id=dr${i} value="${esc(d.rxgain||0)}"></div><div><label>TX gain</label><input id=dt${i} value="${esc(d.txgain||0)}"></div></div><button class=btn onclick="delDongle(${i})">Remover</button></div>`).join('')}<div class=actions><button class=btn onclick=addDongle()>+ Dongle</button><button class="btn primary" onclick=saveDongles()>Guardar e aplicar</button><button class=btn onclick="dongleShow()">Estado dongles</button></div><hr><h3>SMS</h3><div class=row><input id=smsdev placeholder=dongle0><input id=smsnum placeholder="+351..."><input id=smstext placeholder="Mensagem"></div><button class=btn onclick=sendSMS()>Enviar SMS</button><h3>USSD</h3><div class=row><input id=ussddev placeholder=dongle0><input id=ussdcode placeholder="*#123#"></div><button class=btn onclick=sendUSSD()>Enviar USSD</button><pre id=gout></pre></div>`}
function addDongle(){let i=(pbx.gsm_dongles||[]).length;pbx.gsm_dongles=pbx.gsm_dongles||[];pbx.gsm_dongles.push({name:'dongle'+i,audio:'/dev/ttyUSB1',data:'/dev/ttyUSB2',context:'from-dongle',group:0,rxgain:0,txgain:0});gsm(E('#app'))}function delDongle(i){pbx.gsm_dongles.splice(i,1);gsm(E('#app'))}
async function saveDongles(){pbx.gsm_dongles=(pbx.gsm_dongles||[]).map((d,i)=>({name:E('#dn'+i).value,audio:E('#da'+i).value,data:E('#dd'+i).value,context:E('#dc'+i).value,group:+E('#dg'+i).value,rxgain:+E('#dr'+i).value,txgain:+E('#dt'+i).value,autodeletesms:true,disablesms:false}));await savePbx()}
async function dongleShow(){let r=await api('api/action',{method:'POST',body:JSON.stringify({action:'dongle_show'})});E('#gout').textContent=r.output}async function sendSMS(){let r=await api('api/action',{method:'POST',body:JSON.stringify({action:'sms',device:E('#smsdev').value,number:E('#smsnum').value,message:E('#smstext').value})});E('#gout').textContent=r.output}async function sendUSSD(){let r=await api('api/action',{method:'POST',body:JSON.stringify({action:'ussd',device:E('#ussddev').value,code:E('#ussdcode').value})});E('#gout').textContent=r.output}
async function calls(a){let r=await api('api/calls');a.innerHTML=`<div class=grid><div class=card><h2>Canais</h2><pre>${esc(r.channels)}</pre></div><div class=card><h2>Endpoints</h2><pre>${esc(r.endpoints)}</pre></div><div class=card><h2>Filas</h2><pre>${esc(r.queues)}</pre></div><div class=card><h2>Conferências</h2><pre>${esc(r.confbridge)}</pre></div></div>`}
async function configs(a){let r=await api('api/files');a.innerHTML=`<div class=card><h2>Editor de configuração</h2><div class=row><select id=fsel onchange=loadFile()>${r.files.map(f=>`<option>${esc(f)}</option>`).join('')}</select></div><textarea id=ftext></textarea><div class=actions><button class="btn primary" onclick=saveFile()>Guardar + reload</button></div></div>`;loadFile()}
async function loadFile(){let f=E('#fsel').value;let r=await api('api/file?name='+encodeURIComponent(f));E('#ftext').value=r.content||''}async function saveFile(){let f=E('#fsel').value;let r=await api('api/file?name='+encodeURIComponent(f),{method:'PUT',body:JSON.stringify({content:E('#ftext').value})});alert(r.ok?'Guardado':'Erro: '+r.error)}
async function logs(a){let r=await api('api/logs');a.innerHTML=`<div class=card><h2>Logs Asterisk</h2><button class=btn onclick=render()>Atualizar</button><pre style="max-height:70vh">${esc(r.output)}</pre></div>`}
async function diag(a){let r=await api('api/diagnostics');a.innerHTML=`<div class=grid><div class=card><h2>Módulos</h2><pre>${esc(r.modules)}</pre></div><div class=card><h2>PJSIP</h2><pre>${esc(r.pjsip)}</pre></div><div class=card><h2>Dongle</h2><pre>${esc(r.dongle)}</pre></div><div class=card><h2>USB</h2><pre>${esc(r.usb)}</pre></div></div>`}
async function savePbx(){let r=await api('api/pbx',{method:'POST',body:JSON.stringify(pbx)});alert(r.ok?'Configuração aplicada':'Erro: '+r.error);render()}
nav();render();setInterval(()=>{if(current==='Dashboard')render()},15000)
</script></body></html>'''

class H(BaseHTTPRequestHandler):
    def log_message(self,*a): pass
    def sendj(self,obj,code=200):
        b=json.dumps(obj,ensure_ascii=False).encode(); self.send_response(code); self.send_header('Content-Type','application/json; charset=utf-8'); self.send_header('Cache-Control','no-store'); self.send_header('Content-Length',len(b)); self.end_headers(); self.wfile.write(b)
    def body(self):
        try: return json.loads(self.rfile.read(int(self.headers.get('Content-Length','0') or 0)) or b'{}')
        except Exception: return {}
    def do_GET(self):
        u=urlparse(self.path); path=u.path.rstrip('/') or '/'; q=parse_qs(u.query)
        if path=='/':
            b=INDEX.encode(); self.send_response(200); self.send_header('Content-Type','text/html; charset=utf-8'); self.send_header('Content-Length',len(b)); self.end_headers(); self.wfile.write(b); return
        if path=='/api/status':
            v=ast('core show version'); ch=ast('core show channels count'); m=re.search(r'(\d+) active channel',ch['output'])
            self.sendj({'running':v['ok'],'version':v['output'].strip(),'channels':int(m.group(1)) if m else 0}); return
        if path=='/api/pbx': self.sendj(load_json(PBX,{})); return
        if path=='/api/usb': self.sendj(usb_ports()); return
        if path=='/api/calls': self.sendj({'channels':ast('core show channels concise')['output'],'endpoints':ast('pjsip show endpoints')['output'],'queues':ast('queue show')['output'],'confbridge':ast('confbridge list')['output']}); return
        if path=='/api/files': self.sendj({'files':sorted([p.name for p in CONF.glob('*.conf')])}); return
        if path=='/api/file':
            n=(q.get('name') or [''])[0]
            if not re.fullmatch(r'[A-Za-z0-9_.-]+\.conf',n) or not (CONF/n).exists(): self.sendj({'error':'invalid file'},404); return
            self.sendj({'name':n,'content':(CONF/n).read_text(errors='ignore')}); return
        if path=='/api/logs': self.sendj(run('tail -n 600 /var/log/asterisk/full 2>/dev/null || tail -n 600 /var/log/asterisk/messages 2>/dev/null')); return
        if path=='/api/diagnostics': self.sendj({'modules':ast('module show like res_ari')['output']+'\n'+ast('module show like chan_dongle')['output'],'pjsip':ast('pjsip show transports')['output']+'\n'+ast('pjsip show contacts')['output'],'dongle':ast('dongle show devices')['output'],'usb':run('lsusb; echo; ls -l /dev/ttyUSB* /dev/ttyACM* 2>/dev/null')['output']}); return
        if path=='/api/credentials': self.sendj(load_json(SEC,{})); return
        self.sendj({'error':'not found'},404)
    def do_POST(self):
        u=urlparse(self.path); data=self.body()
        if u.path.rstrip('/')=='/api/pbx':
            try:
                if not isinstance(data,dict): raise ValueError('object required')
                save_json(PBX,data); render_managed(data); out=ast('core reload'); self.sendj({'ok':True,'reload':out['output']});
            except Exception as e:self.sendj({'ok':False,'error':str(e)},400)
            return
        if u.path.rstrip('/')=='/api/action':
            action=data.get('action','')
            if action=='cli':
                c=str(data.get('command',''))
                allowed=('core reload','pjsip reload','module reload chan_dongle.so','dialplan reload','voicemail reload','queue reload all')
                if c not in allowed:self.sendj({'ok':False,'output':'Command not allowed'},403);return
                self.sendj(ast(c));return
            if action=='dongle_show': self.sendj(ast('dongle show devices'));return
            if action in ('sms','ussd'):
                dev=re.sub(r'[^0-9A-Za-z_-]','',str(data.get('device','')))
                if action=='sms':
                    num=re.sub(r'[^0-9+#*]','',str(data.get('number',''))); msg=str(data.get('message','')).replace('\n',' ').replace('"','').strip()[:500]
                    self.sendj(ast(f'dongle sms {dev} {num} {msg}'));return
                code=re.sub(r'[^0-9*#+]','',str(data.get('code',''))); self.sendj(ast(f'dongle ussd {dev} {code}'));return
            self.sendj({'ok':False,'output':'Unknown action'},400);return
        self.sendj({'error':'not found'},404)
    def do_PUT(self):
        u=urlparse(self.path); q=parse_qs(u.query); data=self.body()
        if u.path.rstrip('/')=='/api/file':
            n=(q.get('name') or [''])[0]
            if not re.fullmatch(r'[A-Za-z0-9_.-]+\.conf',n) or not (CONF/n).exists(): self.sendj({'ok':False,'error':'invalid file'},400);return
            try:(CONF/n).write_text(str(data.get('content',''))); out=ast('core reload'); self.sendj({'ok':True,'reload':out['output']})
            except Exception as e:self.sendj({'ok':False,'error':str(e)},500)
            return
        self.sendj({'error':'not found'},404)

if __name__=='__main__':
    render_managed(load_json(PBX,{}))
    ThreadingHTTPServer(('0.0.0.0',8099),H).serve_forever()
