INDEX=r'''<!doctype html><html lang="pt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Asterisk HA</title><style>
:root{font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color-scheme:dark;background:#111827;color:#e5e7eb}body{margin:0}.top{padding:18px 22px;background:#0b1220;position:sticky;top:0;z-index:2;border-bottom:1px solid #263244}.top h1{margin:0;font-size:22px}.sub{color:#93a4b8;font-size:13px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.tabs button,.btn{background:#1f2937;color:#eee;border:1px solid #374151;border-radius:9px;padding:9px 12px;cursor:pointer}.tabs button.active,.btn.primary{background:#2563eb}.wrap{padding:18px;max-width:1400px;margin:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px}.card{background:#172033;border:1px solid #263244;border-radius:13px;padding:15px}.big{font-size:25px;font-weight:700}.ok{color:#55d98b}.bad{color:#ff7b7b}.warn{color:#fbbf24}pre,textarea{background:#09101d;color:#dbeafe;border:1px solid #334155;border-radius:9px;padding:10px;overflow:auto}textarea{width:100%;min-height:420px;box-sizing:border-box}input,select{background:#0b1220;color:#eee;border:1px solid #3b4a60;border-radius:8px;padding:8px;box-sizing:border-box;width:100%}input[type=checkbox]{width:auto}label{font-size:12px;color:#a8b6ca}.row{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px;margin:8px 0}.item{padding:10px;border:1px solid #334155;border-radius:9px;margin:8px 0}.actions{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.pill{display:inline-block;padding:4px 8px;border-radius:99px;background:#243247;font-size:12px}.note{background:#0b2942;border:1px solid #155e75;border-radius:9px;padding:10px;margin:10px 0}</style></head><body>
<div class="top"><h1>☎ Asterisk 22 + Home Assistant</h1><div class="sub">PBX · PJSIP · HT503 FXS/FXO · AMI · ARI · Queues · ConfBridge · Voicemail · Recordings · chan_dongle GSM</div><div class="tabs" id="tabs"></div></div><div class="wrap" id="app"></div>
<script>
const tabs=['Dashboard','Extensões','HT503 / FXO','Trunks SIP','GSM / chan_dongle','Chamadas','Configuração','Logs','Diagnóstico'];let current='Dashboard';let pbx={};
const E=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(path,opt={}){let r=await fetch(path,{headers:{'Content-Type':'application/json'},...opt});return await r.json()}
function nav(){E('#tabs').innerHTML=tabs.map(t=>`<button class="${t==current?'active':''}" onclick="current='${t}';nav();render()">${t}</button>`).join('')}
async function render(){let a=E('#app');a.innerHTML='<div class=card>A carregar…</div>';try{pbx=await api('api/pbx')}catch(e){} if(current==='Dashboard') dashboard(a); if(current==='Extensões') extensions(a); if(current==='HT503 / FXO') ht503(a); if(current==='Trunks SIP') trunks(a); if(current==='GSM / chan_dongle') gsm(a); if(current==='Chamadas') calls(a); if(current==='Configuração') configs(a); if(current==='Logs') logs(a); if(current==='Diagnóstico') diag(a)}
async function dashboard(a){let s=await api('api/status');let ht=(pbx.ht503||{});a.innerHTML=`<div class=grid><div class=card><div class=sub>Asterisk</div><div class="big ${s.running?'ok':'bad'}">${s.running?'ONLINE':'OFFLINE'}</div><pre>${esc(s.version||'')}</pre></div><div class=card><div class=sub>Canais ativos</div><div class=big>${s.channels}</div></div><div class=card><div class=sub>Extensões GUI</div><div class=big>${(pbx.extensions||[]).length}</div></div><div class=card><div class=sub>HT503 FXO</div><div class="big ${ht.enabled?'ok':'warn'}">${ht.enabled?'CONFIGURADO':'DESATIVADO'}</div><div class=sub>${esc(ht.fxo_user||'')}</div></div><div class=card><div class=sub>Dongles GSM</div><div class=big>${(pbx.gsm_dongles||[]).length}</div></div></div><div class=actions><button class="btn primary" onclick="cmd('core reload')">Reload Asterisk</button><button class=btn onclick="cmd('pjsip reload')">Reload PJSIP</button><button class=btn onclick="cmd('module reload chan_dongle.so')">Reload chan_dongle</button></div>`}
async function cmd(c){let r=await api('api/action',{method:'POST',body:JSON.stringify({action:'cli',command:c})});alert(r.output||JSON.stringify(r));render()}
function extensions(a){let x=pbx.extensions||[];a.innerHTML=`<div class=card><h2>Extensões PJSIP</h2><div class=note>Telefones/ATA que se registam no Asterisk. Para a porta FXO do Grandstream HT503 usa o separador <b>HT503 / FXO</b>, não Trunks SIP.</div><div id=elist>${x.map((e,i)=>`<div class=item><div class=row><div><label>Extensão</label><input id=e${i} value="${esc(e.extension)}"></div><div><label>Caller ID</label><input id=c${i} value="${esc(e.callerid)}"></div><div><label>Password SIP</label><input id=s${i} value="${esc(e.secret)}"></div><div><label>PIN Voicemail</label><input id=v${i} value="${esc(e.voicemail_pin||'1234')}"></div><div><label>Contexto</label><input id=x${i} value="${esc(e.context||'from-internal')}"></div></div><button class=btn onclick="delExt(${i})">Remover</button></div>`).join('')}</div><div class=actions><button class=btn onclick=addExt()>+ Extensão</button><button class="btn primary" onclick=saveExt()>Guardar e aplicar</button></div></div>`}
function addExt(){pbx.extensions=pbx.extensions||[];pbx.extensions.push({extension:String(100+pbx.extensions.length),callerid:'Nova extensão',secret:Math.random().toString(36).slice(2,14),voicemail_pin:'1234',context:'from-internal'});extensions(E('#app'))}function delExt(i){pbx.extensions.splice(i,1);extensions(E('#app'))}
async function saveExt(){pbx.extensions=(pbx.extensions||[]).map((e,i)=>({extension:E('#e'+i).value,callerid:E('#c'+i).value,secret:E('#s'+i).value,voicemail_pin:E('#v'+i).value,context:E('#x'+i).value}));await savePbx()}
async function ht503(a){let h=pbx.ht503||{enabled:false,device_ip:'',fxo_user:'ht503fxo',fxo_secret:'',callerid:'Exterior',incoming_target:'100',outbound_prefix:'8',local_sip_port:5064};let st=h.enabled?await api('api/ht503-status'):{};a.innerHTML=`<div class=card><h2>Grandstream HT503 — porta FXO / linha exterior</h2><div class=note><b>Direção correta:</b> o HT503 regista-se no Asterisk. Aqui não é criado nenhum <code>type=registration</code> outbound. No HT503: Primary SIP Server = IP deste Asterisk; SIP User ID e Authenticate ID = o utilizador abaixo; SIP Registration = Yes.</div><div class=row><div><label>Ativar HT503 FXO</label><select id=hen><option value=0 ${h.enabled?'':'selected'}>Não</option><option value=1 ${h.enabled?'selected':''}>Sim</option></select></div><div><label>IP do HT503 (informativo)</label><input id=hip value="${esc(h.device_ip||'')}" placeholder="192.168.1.100"></div><div><label>Utilizador FXO / SIP User ID</label><input id=huser value="${esc(h.fxo_user||'ht503fxo')}"></div><div><label>Password / Authenticate Password</label><input id=hsec type=password value="${esc(h.fxo_secret||'')}"></div><div><label>Caller ID</label><input id=hcid value="${esc(h.callerid||'Exterior')}"></div><div><label>Extensão destino de chamadas PSTN</label><input id=htarget value="${esc(h.incoming_target||'100')}"></div><div><label>Prefixo para chamadas PSTN</label><input id=hpre value="${esc(h.outbound_prefix||'8')}"></div><div><label>Porta SIP local do FXO (informativo)</label><input id=hport value="${esc(h.local_sip_port||5064)}"></div></div><div class=actions><button class="btn primary" onclick=saveHT()>Guardar e aplicar</button><button class=btn onclick=ht503(E('#app'))>Atualizar estado</button></div>${h.enabled?`<h3>Estado PJSIP</h3><pre>${esc(st.endpoint||'')}
${esc(st.contacts||'')}</pre>`:''}</div>`}
async function saveHT(){pbx.ht503={enabled:E('#hen').value==='1',device_ip:E('#hip').value,fxo_user:E('#huser').value,fxo_secret:E('#hsec').value,callerid:E('#hcid').value,incoming_target:E('#htarget').value,outbound_prefix:E('#hpre').value,local_sip_port:+E('#hport').value};await savePbx()}
function trunks(a){let x=pbx.sip_trunks||[];a.innerHTML=`<div class=card><h2>Trunks SIP/PJSIP</h2><div class=note>Usa esta página para operadores/servidores SIP nos quais o <b>Asterisk se regista</b>. Não uses aqui o HT503.</div>${x.map((t,i)=>`<div class=item><div class=row><div><label>Nome</label><input id=tn${i} value="${esc(t.name)}"></div><div><label>Servidor</label><input id=th${i} value="${esc(t.server)}"></div><div><label>Utilizador</label><input id=tu${i} value="${esc(t.username)}"></div><div><label>Password</label><input id=tp${i} value="${esc(t.password)}"></div><div><label>Porta</label><input id=tport${i} value="${esc(t.port||5060)}"></div><div><label>Prefixo saída</label><input id=tpre${i} value="${esc(t.prefix||'0')}"></div></div><button class=btn onclick="delTrunk(${i})">Remover</button></div>`).join('')}<div class=actions><button class=btn onclick=addTrunk()>+ Trunk</button><button class="btn primary" onclick=saveTrunks()>Guardar e aplicar</button></div></div>`}
function addTrunk(){pbx.sip_trunks=pbx.sip_trunks||[];pbx.sip_trunks.push({name:'trunk'+(pbx.sip_trunks.length+1),server:'',username:'',password:'',port:5060,prefix:'0'});trunks(E('#app'))}function delTrunk(i){pbx.sip_trunks.splice(i,1);trunks(E('#app'))}
async function saveTrunks(){pbx.sip_trunks=(pbx.sip_trunks||[]).map((t,i)=>({name:E('#tn'+i).value,server:E('#th'+i).value,username:E('#tu'+i).value,password:E('#tp'+i).value,port:+E('#tport'+i).value,prefix:E('#tpre'+i).value}));await savePbx()}
async function gsm(a){let ports=await api('api/usb');let x=pbx.gsm_dongles||[];let opts=ports.map(p=>`<option value="${esc(p.device)}">${esc(p.device)} ${esc(p.id_vendor||'')} ${esc(p.id_model||'')} IF:${esc(p.id_usb_interface_num||'')}</option>`).join('');a.innerHTML=`<div class=card><h2>chan_dongle / GSM</h2><p>Portas detetadas: <span class=pill>${ports.length}</span></p><pre>${esc(JSON.stringify(ports,null,2))}</pre>${x.map((d,i)=>`<div class=item><div class=row><div><label>Nome</label><input id=dn${i} value="${esc(d.name)}"></div><div><label>Áudio</label><select id=da${i}><option>${esc(d.audio||'')}</option>${opts}</select></div><div><label>Dados/AT</label><select id=dd${i}><option>${esc(d.data||'')}</option>${opts}</select></div><div><label>Contexto</label><input id=dc${i} value="${esc(d.context||'from-dongle')}"></div><div><label>Grupo</label><input id=dg${i} value="${esc(d.group||0)}"></div><div><label>RX gain</label><input id=dr${i} value="${esc(d.rxgain||0)}"></div><div><label>TX gain</label><input id=dt${i} value="${esc(d.txgain||0)}"></div></div><button class=btn onclick="delDongle(${i})">Remover</button></div>`).join('')}<div class=actions><button class=btn onclick=addDongle()>+ Dongle</button><button class="btn primary" onclick=saveDongles()>Guardar e aplicar</button><button class=btn onclick="dongleShow()">Estado dongles</button></div><hr><h3>SMS</h3><div class=row><input id=smsdev placeholder=dongle0><input id=smsnum placeholder="+351..."><input id=smstext placeholder="Mensagem"></div><button class=btn onclick=sendSMS()>Enviar SMS</button><h3>USSD</h3><div class=row><input id=ussddev placeholder=dongle0><input id=ussdcode placeholder="*#123#"></div><button class=btn onclick=sendUSSD()>Enviar USSD</button><pre id=gout></pre></div>`}
function addDongle(){let i=(pbx.gsm_dongles||[]).length;pbx.gsm_dongles=pbx.gsm_dongles||[];pbx.gsm_dongles.push({name:'dongle'+i,audio:'/dev/ttyUSB1',data:'/dev/ttyUSB2',context:'from-dongle',group:0,rxgain:0,txgain:0});gsm(E('#app'))}function delDongle(i){pbx.gsm_dongles.splice(i,1);gsm(E('#app'))}
async function saveDongles(){pbx.gsm_dongles=(pbx.gsm_dongles||[]).map((d,i)=>({name:E('#dn'+i).value,audio:E('#da'+i).value,data:E('#dd'+i).value,context:E('#dc'+i).value,group:+E('#dg'+i).value,rxgain:+E('#dr'+i).value,txgain:+E('#dt'+i).value,autodeletesms:true,disablesms:false}));await savePbx()}
async function dongleShow(){let r=await api('api/action',{method:'POST',body:JSON.stringify({action:'dongle_show'})});E('#gout').textContent=r.output}async function sendSMS(){let r=await api('api/action',{method:'POST',body:JSON.stringify({action:'sms',device:E('#smsdev').value,number:E('#smsnum').value,message:E('#smstext').value})});E('#gout').textContent=r.output}async function sendUSSD(){let r=await api('api/action',{method:'POST',body:JSON.stringify({action:'ussd',device:E('#ussddev').value,code:E('#ussdcode').value})});E('#gout').textContent=r.output}
async function calls(a){let r=await api('api/calls');a.innerHTML=`<div class=grid><div class=card><h2>Canais</h2><pre>${esc(r.channels)}</pre></div><div class=card><h2>Endpoints</h2><pre>${esc(r.endpoints)}</pre></div><div class=card><h2>Filas</h2><pre>${esc(r.queues)}</pre></div><div class=card><h2>Conferências</h2><pre>${esc(r.confbridge)}</pre></div></div>`}
async function configs(a){let r=await api('api/files');a.innerHTML=`<div class=card><h2>Editor de configuração</h2><div class=row><select id=fsel onchange=loadFile()>${r.files.map(f=>`<option>${esc(f)}</option>`).join('')}</select></div><textarea id=ftext></textarea><div class=actions><button class="btn primary" onclick=saveFile()>Guardar + reload</button></div></div>`;loadFile()}
async function loadFile(){let f=E('#fsel').value;let r=await api('api/file?name='+encodeURIComponent(f));E('#ftext').value=r.content||''}async function saveFile(){let f=E('#fsel').value;let r=await api('api/file?name='+encodeURIComponent(f),{method:'PUT',body:JSON.stringify({content:E('#ftext').value})});alert(r.ok?'Guardado':'Erro: '+r.error)}
async function logs(a){let r=await api('api/logs');a.innerHTML=`<div class=card><h2>Logs Asterisk</h2><button class=btn onclick=render()>Atualizar</button><pre style="max-height:70vh">${esc(r.output)}</pre></div>`}
async function diag(a){let r=await api('api/diagnostics');a.innerHTML=`<div class=grid><div class=card><h2>Módulos</h2><pre>${esc(r.modules)}</pre></div><div class=card><h2>PJSIP</h2><pre>${esc(r.pjsip)}</pre></div><div class=card><h2>Dongle</h2><pre>${esc(r.dongle)}</pre></div><div class=card><h2>USB</h2><pre>${esc(r.usb)}</pre></div></div>`}
async function savePbx(){let r=await api('api/pbx',{method:'POST',body:JSON.stringify(pbx)});alert(r.ok?'Configuração aplicada':'Erro: '+r.error);render()}
nav();render();setInterval(()=>{if(current==='Dashboard')render()},60000)
</script></body></html>'''
