#!/usr/bin/env python3
import json
import re
import subprocess
import time
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

STATE = Path('/config/state/wakeup.json')
OPTIONS = Path('/data/options.json')
CONF = '/config/asterisk/asterisk.conf'
HEARTBEAT = Path('/run/asterisk-wakeup-heartbeat')
SOUNDS = Path('/var/lib/asterisk/sounds')
WAKEUP_DIALPLAN_HELPER = '/opt/asterisk-ha/wakeup_dialplan.py'
WAKEUP_ENGINE_VERSION = '0.2.28'
DEFAULT_WAKEUP_SOUND = 'ha/wakeup-pt'
LEGACY_PORTUGUESE_SOUND = 'pt_BR/this-is-yr-wakeup-call'
CLASSIC_WAKEUP_SOUND = 'this-is-yr-wakeup-call'
CLASSIC_WAKEUP_FILE = 'en/this-is-yr-wakeup-call'
SOUND_EXTENSIONS = ('.wav', '.WAV', '.gsm', '.ulaw', '.alaw', '.g722', '.sln', '.sln16')


def _read_json(path, default):
    try:
        return json.loads(Path(path).read_text())
    except Exception:
        return default


def _write_json(path, data):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + '.tmp')
    tmp.write_text(json.dumps(data, indent=2, ensure_ascii=False))
    tmp.replace(path)


def _extension(value):
    return re.sub(r'[^0-9]', '', str(value or ''))[:12]


def _time(value):
    raw = str(value or '').strip()
    if not re.fullmatch(r'(?:[01]\d|2[0-3]):[0-5]\d', raw):
        raise ValueError('hora inválida; usa HH:MM')
    return raw


def _date(value):
    raw = str(value or '').strip()
    if not raw:
        return ''
    datetime.strptime(raw, '%Y-%m-%d')
    return raw


def _sound(value):
    raw = str(value or DEFAULT_WAKEUP_SOUND).strip() or DEFAULT_WAKEUP_SOUND
    if not re.fullmatch(r'[0-9A-Za-z_./-]+', raw):
        raise ValueError('som inválido')
    return raw[:160]


def _sound_exists(sound):
    sound = _sound(sound)
    base = SOUNDS / sound
    if base.is_file():
        return True
    return any(Path(str(base) + ext).is_file() for ext in SOUND_EXTENSIONS)


def _classic_sound_available():
    return _sound_exists(CLASSIC_WAKEUP_FILE) or _sound_exists(CLASSIC_WAKEUP_SOUND)


def resolve_wakeup_sound(requested=None):
    """Report the prompt that the dedicated dialplan will attempt first."""
    if _sound_exists(DEFAULT_WAKEUP_SOUND):
        return DEFAULT_WAKEUP_SOUND
    if _classic_sound_available():
        return CLASSIC_WAKEUP_SOUND
    return 'dialplan-fallback'


def normalize_alarm(item, fallback_id=1):
    if not isinstance(item, dict):
        raise ValueError('despertador inválido')
    days = []
    for x in (item.get('days') or []):
        try:
            x = int(x)
            if 0 <= x <= 6 and x not in days:
                days.append(x)
        except Exception:
            pass
    ext = _extension(item.get('extension'))
    if not ext:
        raise ValueError('extensão obrigatória')
    alarm_id = re.sub(r'[^0-9A-Za-z_-]', '', str(item.get('id') or f'alarm{fallback_id}'))[:40] or f'alarm{fallback_id}'
    raw_sound = str(item.get('sound') or '').strip()
    # Migrate all old built-in wake-up defaults to the deterministic prompt
    # generated by this add-on. User-defined custom names are preserved.
    if raw_sound in ('', 'beep', LEGACY_PORTUGUESE_SOUND, CLASSIC_WAKEUP_SOUND, CLASSIC_WAKEUP_FILE):
        raw_sound = DEFAULT_WAKEUP_SOUND
    return {
        'id': alarm_id,
        'enabled': bool(item.get('enabled', True)),
        'label': re.sub(r'[\r\n]+', ' ', str(item.get('label') or 'Serviço Despertar'))[:80],
        'extension': ext,
        'time': _time(item.get('time') or '07:00'),
        'days': sorted(days),
        'date': _date(item.get('date')),
        'sound': _sound(raw_sound),
        'last_fired': str(item.get('last_fired') or '')[:32],
    }


def load_state():
    raw = _read_json(STATE, {'alarms': [], 'events': []})
    alarms = []
    for i, item in enumerate(raw.get('alarms') or [], start=1):
        try:
            alarms.append(normalize_alarm(item, i))
        except Exception:
            continue
    return {'alarms': alarms, 'events': list(raw.get('events') or [])[-50:]}


def save_alarms(alarms):
    state = load_state()
    normalized = [normalize_alarm(x, i + 1) for i, x in enumerate(alarms or [])]
    ids = set()
    for alarm in normalized:
        base = alarm['id']; candidate = base; n = 2
        while candidate in ids:
            candidate = f'{base}-{n}'; n += 1
        alarm['id'] = candidate; ids.add(candidate)
    state['alarms'] = normalized
    _write_json(STATE, state)
    return state


def _event(state, text):
    state.setdefault('events', []).append({'at': datetime.now().isoformat(timespec='seconds'), 'text': str(text)[:500]})
    state['events'] = state['events'][-50:]


def _run(cmd, timeout=20):
    try:
        p = subprocess.run(cmd, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=timeout)
        return p.returncode, (p.stdout or '')[-6000:]
    except Exception as exc:
        return 99, str(exc)


def _prepare_wakeup_context():
    """Reinstall, reload and verify the persistent [wakeup-call] context."""
    helper_rc, helper_out = _run(['/usr/bin/python3', WAKEUP_DIALPLAN_HELPER], 10)
    reload_rc, reload_out = _run(['asterisk', '-C', CONF, '-rx', 'dialplan reload'], 15)
    show_rc, show_out = _run(['asterisk', '-C', CONF, '-rx', 'dialplan show wakeup-call'], 15)
    low = show_out.lower()
    present = (
        show_rc == 0
        and 'wakeup-call' in low
        and ('extension' in low or "'s'" in low or ' s ' in low)
        and 'not found' not in low
        and 'no such context' not in low
    )
    return {
        'ok': bool(helper_rc == 0 and reload_rc == 0 and present),
        'helper_rc': helper_rc,
        'reload_rc': reload_rc,
        'show_rc': show_rc,
        'helper_output': helper_out,
        'reload_output': reload_out,
        'show_output': show_out,
    }


def _asterisk_originate(extension, sound=DEFAULT_WAKEUP_SOUND):
    """Ring the extension and run the verified [wakeup-call] dialplan."""
    ext = _extension(extension)
    requested = _sound(sound)
    snd = resolve_wakeup_sound(requested)
    if not ext:
        return {'ok': False, 'output': 'extensão inválida', 'engine_version': WAKEUP_ENGINE_VERSION}

    prepared = _prepare_wakeup_context()
    if not prepared.get('ok'):
        diag = (
            'O contexto [wakeup-call] não ficou carregado.\n'
            f"helper rc={prepared.get('helper_rc')} {prepared.get('helper_output','')}\n"
            f"reload rc={prepared.get('reload_rc')} {prepared.get('reload_output','')}\n"
            f"show rc={prepared.get('show_rc')} {prepared.get('show_output','')}"
        )
        return {
            'ok': False,
            'output': diag[-6000:],
            'extension': ext,
            'sound': snd,
            'requested_sound': requested,
            'call_mode': 'dialplan:wakeup-call',
            'engine_version': WAKEUP_ENGINE_VERSION,
            'dialplan_ready': False,
        }

    cmd = ['asterisk', '-C', CONF, '-rx', f'channel originate PJSIP/{ext} extension s@wakeup-call']
    rc, out = _run(cmd, 70)
    return {
        'ok': rc == 0,
        'output': out,
        'extension': ext,
        'sound': snd,
        'requested_sound': requested,
        'call_mode': 'dialplan:wakeup-call',
        'engine_version': WAKEUP_ENGINE_VERSION,
        'dialplan_ready': True,
    }


def test_alarm(extension, sound=DEFAULT_WAKEUP_SOUND):
    return _asterisk_originate(extension, sound)


def _timezone():
    opt = _read_json(OPTIONS, {})
    name = str(opt.get('timezone') or 'Europe/Lisbon')
    try:
        return ZoneInfo(name), name
    except Exception:
        return ZoneInfo('Europe/Lisbon'), 'Europe/Lisbon'


def status():
    state = load_state()
    try:
        age = time.time() - HEARTBEAT.stat().st_mtime
        scheduler_online = age < 35
    except Exception:
        scheduler_online = False
    tz, tz_name = _timezone()
    now = datetime.now(tz)
    classic_available = _classic_sound_available()
    bundled_available = _sound_exists(DEFAULT_WAKEUP_SOUND)
    return {
        **state,
        'scheduler_online': scheduler_online,
        'timezone': tz_name,
        'now': now.isoformat(timespec='seconds'),
        'active': sum(1 for x in state['alarms'] if x.get('enabled')),
        'default_prompt': DEFAULT_WAKEUP_SOUND,
        'resolved_prompt': resolve_wakeup_sound(DEFAULT_WAKEUP_SOUND),
        'portuguese_prompt_available': bundled_available,
        'bundled_prompt_available': bundled_available,
        'classic_prompt_available': classic_available,
        'call_mode': 'dialplan:wakeup-call',
        'engine_version': WAKEUP_ENGINE_VERSION,
    }


def scheduler_loop():
    HEARTBEAT.parent.mkdir(parents=True, exist_ok=True)
    while True:
        try:
            HEARTBEAT.touch()
            state = load_state()
            tz, _ = _timezone()
            now = datetime.now(tz)
            minute_key = now.strftime('%Y-%m-%dT%H:%M')
            changed = False
            for alarm in state['alarms']:
                if not alarm.get('enabled') or alarm.get('time') != now.strftime('%H:%M'):
                    continue
                if alarm.get('date'):
                    if alarm['date'] != now.strftime('%Y-%m-%d'):
                        continue
                elif alarm.get('days') and now.weekday() not in alarm['days']:
                    continue
                if alarm.get('last_fired') == minute_key:
                    continue
                result = _asterisk_originate(alarm['extension'], alarm.get('sound') or DEFAULT_WAKEUP_SOUND)
                alarm['last_fired'] = minute_key
                if alarm.get('date'):
                    alarm['enabled'] = False
                _event(state, f"{alarm['label']} → {alarm['extension']} @ {alarm['time']}: {'OK' if result.get('ok') else 'ERRO'} engine={result.get('engine_version','')} mode={result.get('call_mode','')} prompt={result.get('sound','')} {result.get('output','')}")
                changed = True
            if changed:
                _write_json(STATE, state)
        except Exception:
            pass
        time.sleep(10)
