[cel_master.csv]
format=dsv
separator_character=,
quote_character="
quote_escape_character="
quoting_method=all
fields=EventType,EventTime,CIDName,CIDNum,Exten,Context,ChanName,AppName,AppData,AMAFlags(amaflags),AccountCode,UniqueID(noquote),LinkedID(noquote),Peer,PeerAccount,UserField,EventExtra,TenantID
