[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]
RECORDING_DIR=/share/asterisk-recordings

[from-internal]
exten => *43,1,Echo()
exten => *60,1,Answer()
 same => n,SayUnixTime()
 same => n,Hangup()
exten => *97,1,VoiceMailMain(${CALLERID(num)}@default)
exten => _*98X.,1,VoiceMailMain(${EXTEN:3}@default)
#include extensions_gui.conf

[from-dongle]
#include extensions_dongle_gui.conf
